from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(805, 618)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        
        self.Load_Image_1 = QtWidgets.QPushButton(Dialog)
        self.Load_Image_1.setGeometry(QtCore.QRect(30, 240, 93, 28))
        self.Load_Image_1.setObjectName("Load_Image_1")
        
        self.Load_image_2 = QtWidgets.QPushButton(Dialog)
        self.Load_image_2.setGeometry(QtCore.QRect(30, 310, 93, 28))
        self.Load_image_2.setObjectName("Load_image_2")
        
        self.image_processing = QtWidgets.QGroupBox(Dialog)
        self.image_processing.setGeometry(QtCore.QRect(180, 50, 181, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_processing.sizePolicy().hasHeightForWidth())
        self.image_processing.setSizePolicy(sizePolicy)
        self.image_processing.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.image_processing.setObjectName("image_processing")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.image_processing)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 20, 160, 124))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Image_processing = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Image_processing.setContentsMargins(0, 0, 0, 0)
        self.Image_processing.setSpacing(19)
        self.Image_processing.setObjectName("Image_processing")

        self.color_separation = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.color_separation.setObjectName("color_separation")
        self.Image_processing.addWidget(self.color_separation)
        
        self.color_transformation = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.color_transformation.setObjectName("color_transformation")
        self.Image_processing.addWidget(self.color_transformation)
        
        self.color_extraction = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.color_extraction.setObjectName("color_extraction")
        self.Image_processing.addWidget(self.color_extraction)
        
        self.image_smoothing = QtWidgets.QGroupBox(Dialog)
        self.image_smoothing.setGeometry(QtCore.QRect(180, 300, 171, 151))
        
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_smoothing.sizePolicy().hasHeightForWidth())
        self.image_smoothing.setSizePolicy(sizePolicy)
        self.image_smoothing.setObjectName("image_smoothing")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.image_smoothing)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(0, 20, 160, 124))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.Image_processing_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.Image_processing_4.setContentsMargins(0, 0, 0, 0)
        self.Image_processing_4.setSpacing(19)
        self.Image_processing_4.setObjectName("Image_processing_4")
        self.gaussian_filter = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.gaussian_filter.setObjectName("gaussian_filter")
        self.Image_processing_4.addWidget(self.gaussian_filter)
        self.bilateral_filter = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.bilateral_filter.setObjectName("bilateral_filter")
        self.Image_processing_4.addWidget(self.bilateral_filter)
        self.median_fliter = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.median_fliter.setObjectName("median_fliter")
        self.Image_processing_4.addWidget(self.median_fliter)
        self.edge_detection_2 = QtWidgets.QGroupBox(Dialog)
        self.edge_detection_2.setGeometry(QtCore.QRect(450, 50, 191, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edge_detection_2.sizePolicy().hasHeightForWidth())
        self.edge_detection_2.setSizePolicy(sizePolicy)
        self.edge_detection_2.setObjectName("edge_detection_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.edge_detection_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 20, 191, 171))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.edge_detection = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.edge_detection.setContentsMargins(0, 0, 0, 0)
        self.edge_detection.setSpacing(19)
        self.edge_detection.setObjectName("edge_detection")
        self.sobel_x = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.sobel_x.setObjectName("sobel_x")
        self.edge_detection.addWidget(self.sobel_x)
        self.sobel_y = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.sobel_y.setObjectName("sobel_y")
        self.edge_detection.addWidget(self.sobel_y)
        self.combination_and_threshold = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.combination_and_threshold.setObjectName("combination_and_threshold")
        self.edge_detection.addWidget(self.combination_and_threshold)
        self.gradiant_angle = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.gradiant_angle.setObjectName("gradiant_angle")
        self.edge_detection.addWidget(self.gradiant_angle)
        self.Transform = QtWidgets.QGroupBox(Dialog)
        self.Transform.setGeometry(QtCore.QRect(450, 300, 261, 241))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Transform.sizePolicy().hasHeightForWidth())
        self.Transform.setSizePolicy(sizePolicy)
        self.Transform.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Transform.setObjectName("Transform")
        self.gridLayoutWidget = QtWidgets.QWidget(self.Transform)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 211, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.Tx = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.Tx.setObjectName("Tx")
        self.gridLayout.addWidget(self.Tx, 2, 1, 1, 1)
        self.scaling = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.scaling.setObjectName("scaling")
        self.gridLayout.addWidget(self.scaling, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.Rotation = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.Rotation.setObjectName("Rotation")
        self.gridLayout.addWidget(self.Rotation, 0, 1, 1, 1)
        self.Ty = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.Ty.setObjectName("Ty")
        self.gridLayout.addWidget(self.Ty, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.Transform)
        self.pushButton.setGeometry(QtCore.QRect(80, 200, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Load_Image_1.setText(_translate("Dialog", "Load Image 1"))
        self.Load_image_2.setText(_translate("Dialog", "Load Image 2"))
        self.image_processing.setTitle(_translate("Dialog", "1.Image processing"))
        self.color_separation.setAccessibleName(_translate("Dialog", "1.1 Color Separation"))
        self.color_separation.setText(_translate("Dialog", "1.1 Color Separation"))
        self.color_transformation.setAccessibleName(_translate("Dialog", "1.2 Color Transformation"))
        self.color_transformation.setText(_translate("Dialog", "1.2 Color Transformation"))
        self.color_extraction.setText(_translate("Dialog", "1.3 Color Extraction"))
        self.image_smoothing.setTitle(_translate("Dialog", "2.Image Smoothing"))
        self.gaussian_filter.setAccessibleName(_translate("Dialog", "1.1 Color Separation"))
        self.gaussian_filter.setText(_translate("Dialog", "2.1 Gaussian Filter"))
        self.bilateral_filter.setAccessibleName(_translate("Dialog", "1.2 Color Transformation"))
        self.bilateral_filter.setText(_translate("Dialog", "2.2 Bilateral Filter"))
        self.median_fliter.setText(_translate("Dialog", "2.3 Median Fliter"))
        self.edge_detection_2.setTitle(_translate("Dialog", "3. Edge Detection"))
        self.sobel_x.setAccessibleName(_translate("Dialog", "1.1 Color Separation"))
        self.sobel_x.setText(_translate("Dialog", "3.1 Sobel X"))
        self.sobel_y.setAccessibleName(_translate("Dialog", "1.2 Color Transformation"))
        self.sobel_y.setText(_translate("Dialog", "3.2 Sobel Y"))
        self.combination_and_threshold.setText(_translate("Dialog", "3.3 combination and threshold"))
        self.gradiant_angle.setText(_translate("Dialog", "3.4 Gradiant Angle"))
        self.Transform.setTitle(_translate("Dialog", "4. Transforms "))
        self.label.setText(_translate("Dialog", "Rotation"))
        self.label_5.setText(_translate("Dialog", "Ty"))
        self.label_4.setText(_translate("Dialog", "Tx"))
        self.label_3.setText(_translate("Dialog", "Scaling"))
        self.label_6.setText(_translate("Dialog", "deg"))
        self.label_8.setText(_translate("Dialog", "pixal"))
        self.label_9.setText(_translate("Dialog", "pixal"))
        self.pushButton.setText(_translate("Dialog", "4.Transform"))